### ISSUE TITLE
VeriStand Instrument Addon USB VISA Read issue(no data) with Wait Type>>Wait Second

### ISSUE THREAD

**Issue by grigg3** [ni/niveristand-instrument-addon-custom-device#190]
****Issue - Internal bug 1720960**
No data read when using the Instrument Addon Custom Device with a USB VISA device with wait type as **Wait Second.** Does not matter if casting to data type or formatting to a String for output to VeriStand screen indicator. No data will be read or displayed to a screen indicator.

**Versions Noted**
Confirmed in VeriStand 2019 R3 and VeriStand 2020 R5 with the 20.4 Instrument Addon Custom Device release from Github.

**Replicating Steps**

1. Create new VeriStand default project and save to a desired test location
2. Open System Definition file using the Configure button
3. Add a new Instrument Addon by right clicking on Custom Devices, then selecting National Instruments>>Instrument Addon
4. Select VISA as protocol
5. Select the applicable VISA resource (tested with Tektronix 2001C USBTMC Oscilloscope)
6. Now create a message group by right clicking the new device from the tree view and selecting Add Group
7. Right click the message group and select Add Message
8. Expand the message group and individual message and configure the message and response
9. For example, for the Tektronix instrument, a "MEASU:MEAS:VAL?" command was used after verifying in a VISA test panel in NI-MAX
10. Configure the response by assigning a variable such as [myMeasurement]
11. Right click on the response and create the data for the response
12. Connect the data to the variable under the Linkage section of the Response entry item from the tree view
13. Navigate to the screen (UI manager)
14. Add an indicator and connect it to the response data
15. Ensure the Wait Type is Wait Second (This is the problem setting while Byte Count works great)
16. Deploy the system definition to Windows LocalHost
17. No data is seen updating in the indicator
18. 

Work Around
Current work around is to use Byte Count and give big enough buffer so that the VISA Read.vi function will complete successfully.

**Root Cause**
The Instrument Addon Custom Device uses an incorrect VISA attribute called **Number of Bytes at Serial Port** when on the Wait Second wait type. This attribute is not applicable to USB or USBTMC devices.

1. Using source code, navigate to Instrument Addon Engine.llb>>Protocol Engine.vi See screenshot below of Protocol Engine.viProtocol Engine Code.png
2. Double click on Read function (icon with glasses) to view the different Class definitions for reading different instrumentsProtocol Engine Class VISA class Read.png
3. Note the bad VISA attribute [VI_ATTR_ASRL_AVAIL_NUM on page 3-4 of programmers manual](https://www.ni.com/pdf/manuals/370132c.pdf). This is not valid for USB VISA resources as seen in this IO trace log from replicated case.Bad VISA attribute IO trace.png

**Comment by phutanu** [comment]
Hi @grigg3,

We will have a look at this issue.

Thanks,
Paul

**Comment by momo815** [comment]
How can you open the codes normally?
Can it be deployed in NI Linux RT？
