### ISSUE TITLE
I can't open the codes normally .

### ISSUE THREAD

**Issue by momo815** [ni/niveristand-instrument-addon-custom-device#192]
## If you need immediate assistance, please contact NI Support at support@ni.com or 1(800)531-5066.

**Please describe the problem you're facing.**
I can't open the codes normally and  all the Source Dependencies listed in the Instrument Addon Readme.md have been installed .
The  VI paths of  the NationalInstruments.VeriStand.SystemDefinitionAPI and VeriStandTestCase were something wrong .

**Describe the expected behavior**
I hope you can tell me the operating steps and the correct paths of the codes ,
for example,
niveristand-custom-device-testing-tools-main,
niveristand-instrument-addon-classes-main,
niveristand-instrument-addon-custom-device-20.5.0.

**Describe troubleshooting steps you've taken.**
I had tried to open the codes with finding the needed vis, but finally I couldn't  build the engine release to apply in NI Linux RT.
Now the version of windows is still not normal .

the classes of Protections.lvlibp and Protocols.lvlibp  relate to the environment of windows or parlaps or Linux RT.

**Additional context**
The steps I operated were 
1.download the three codes  ：
niveristand-custom-device-testing-tools-main,
niveristand-instrument-addon-classes-main,
niveristand-instrument-addon-custom-device-20.5.0.
2.run the niveristand-instrument-addon-classes-main to get the classes of windows or parlaps or Linux RT.
3.run the niveristand-instrument-addon-custom-device-20.5.0,find the missing vis from the niveristand-custom-device-testing-tools-main（VeriStandTestCase） or the fold of VeriStand 2020(NationalInstruments.VeriStand.SystemDefinitionAPI.dll)

**Comment by momo815** [comment]
What can I do to apply these codes ?

**Comment by Karl-G1** [comment]
@momo815 Why do you need to build this Custom Device from the source code? NI provides builds on the releases page:
https://github.com/ni/niveristand-instrument-addon-custom-device/releases

All you should need to do is to:
1. Download the .zip file of the version of VeriStand you would like to use it with
2. Install the NI Package (.nipkg) files in the .zip file

**Comment by momo815** [comment]
> @momo815 Why do you need to build this Custom Device from the source code? NI provides builds on the releases page: https://github.com/ni/niveristand-instrument-addon-custom-device/releases
> 
> All you should need to do is to:
> 
> 1. Download the .zip file of the version of VeriStand you would like to use it with
> 2. Install the NI Package (.nipkg) files in the .zip file

How do you generate  the custom device according to your instructions ?There is no custom device for installing only the above or dependent drivers .

**Comment by Karl-G1** [comment]
@momo815 
If there is no custom device installed for VeriStand 2020, you must be installing the wrong package...
Install the package (`ni-instrument-addon-veristand-2020-support_20.5.0.1_windows_x64.nipkg`) contained inside of the `Instrument_Addon_2020.zip` file you can download from the latest release page. This will populate the Custom Devices folder with all of the files needed to use it.

If you are still unable to get the custom device installed, please contact support at the: contact info in the issue header:
contact NI Support at support@ni.com or 1(800)531-5066.

**Comment by Karl-G1** [comment]
Closing from inactivity. Please re-open if this is still an issue.
